[tool.mypy]
strict = true
exclude = "build"

[tool.flake8]
max-line-length = 90
indent-size = 4
exclude = "build"

[tool.pylint]
disable= " line-too-long"  # Already checked by flake8
ignore= " build"

[tool.codespell]
skip = ".git, .github, build"
