[tool.mypy]
strict = true
warn-unreachable = true

[tool.flake8]
max-line-length = 90
indent-size = 4

[tool.pylint]
disable="line-too-long"  # Already checked by flake8

[tool.codespell]
skip = ".git, .github"
