[mypy]
strict = true
exclude = "build"

[flake8]
max-line-length = 90
indent-size = 4
exclude = "build"

[pylint]
disable= " line-too-long"  # Already checked by flake8
ignore= " build"

[codespell]
skip = ".git, .github, build"
